title: Universalization of IC Design in CASS
description: The Universalization of IC Design from CASS (UNIC-CASS) program is a structured end-to-end Integrated Circuit (IC) design-to-test experiential learning. The program aims to improve the know-how and accessibility to IC Design technologies for enthusiasts and design communities worldwide in low-to-middle-income and/or low-opportunity countries. This program is in strategic cooperation with the Solid-State Circuits Society which serves geographically-complementing locations.

theme: just-the-docs

url: https://unic-cass.github.io

aux_links:
  UNIC-CASS Homepage: https://ieee-cas.org/universalization-ic-design-cass-unic-cass

collections:
  training:
    name: "UNIC-CASS Training Materials"
    permalink: "/:collection/:path/"
    output: true
# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2024 IEEE CASS"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/unic-cass/unic-cass.github.io" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

enable_copy_code_button: true

compress_html:
  ignore:
    envs: all
# kramdown:
#   syntax_highlighter_opts:
#     block:
#       line_numbers: true
color_scheme: light
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  cmdout:
    title: Command outputs
    color: grey-dk
  shellcmd:
    title: Terminal
    color: green
  wincmd:
    title: Windows command prompt
    color: green
  video:
    title: Lecture Video
    color: grey-dk
  command:
    color: green